apiVersion: peira.tigera.io/v1alpha1
kind: MockService
metadata:
  namespace: dev
  name: frontend
  labels:
    role: frontend
    log: producer
spec:
  logLevel: debug
  enableProbe: true
  listenPort: 80
  actions:
  - kind: call
    value: http://microservice-1/
  - kind: call
    value: http://microservice-2/
  - kind: call
    value: http://logserver/
  - kind: reply
    value: "hello world"
