apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: operations.log-server
spec:
  ingress:
  - action: Allow
    destination: {}
    source: {}
  egress:
  - action: Allow
    destination: {}
    source: {}
  order: 100
  selector: role == "logserver"
  tier: operations
  types:
  - Ingress
  - Egress
