apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  labels:
    projectcalico.org/tier: default
  name: default.database
  namespace: dev
spec:
  ingress:
  - action: Allow
    destination:
      ports:
      - 80
    protocol: TCP
    source:
      selector: role == "microservice-1"
  - action: Allow
    destination:
      ports:
      - 80
    protocol: TCP
    source:
      selector: role == "microservice-2"
  - action: Deny
    destination: {}
    source: {}
  order: 1000
  selector: role == "database"
  tier: default
  types:
  - Ingress
