apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  labels:
    projectcalico.org/tier: default
  name: default.frontend
  namespace: dev
spec:
  egress:
  - action: Allow
    destination:
      ports:
      - 80
      selector: role == "microservice-1"
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      ports:
      - 80
      selector: role == "microservice-2"
    protocol: TCP
    source: {}
  ingress:
  - action: Allow
    destination:
      ports:
      - 80
    protocol: TCP
    source: {}
  order: 1000
  selector: role == "frontend"
  tier: default
  types:
  - Ingress
  - Egress
