apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security-operations.quarantine
spec:
  egress:
  - action: Log
    destination: {}
    source: {}
  - action: Deny
    destination: {}
    source: {}
  ingress:
  - action: Log
    destination: {}
    source: {}
  - action: Deny
    destination: {}
    source: {}
  order: 200
  selector: quarantine == "true"
  tier: security-operations
  types:
  - Ingress
  - Egress