apiVersion: projectcalico.org/v3
kind: LicenseKey
metadata:
  creationTimestamp: null
  name: default
spec:
  certificate: |+
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQVq3rz5D4nQF1fIgMEh71DzANBgkqhkiG9w0BAQsFADCB
    tTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
    biBGcmFuY2lzY28xFDASBgNVBAoTC1RpZ2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1
    cml0eSA8c2lydEB0aWdlcmEuaW8+MT8wPQYDVQQDEzZUaWdlcmEgRW50aXRsZW1l
    bnRzIEludGVybWVkaWF0ZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTgwNDA1
    MjEzMDI5WhcNMjAxMDA2MjEzMDI5WjCBnjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
    CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC1Rp
    Z2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1cml0eSA8c2lydEB0aWdlcmEuaW8+MSgw
    JgYDVQQDEx9UaWdlcmEgRW50aXRsZW1lbnRzIENlcnRpZmljYXRlMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwg3LkeHTwMi651af/HEXi1tpM4K0LVqb
    5oUxX5b5jjgi+LHMPzMI6oU+NoGPHNqirhAQqK/k7W7r0oaMe1APWzaCAZpHiMxE
    MlsAXmLVUrKg/g+hgrqeije3JDQutnN9h5oZnsg1IneBArnE/AKIHH8XE79yMG49
    LaKpPGhpF8NoG2yoWFp2ekihSohvqKxa3m6pxoBVdwNxN0AfWxb60p2SF0lOi6B3
    hgK6+ILy08ZqXefiUs+GC1Af4qI1jRhPkjv3qv+H1aQVrq6BqKFXwWIlXCXF57CR
    hvUaTOG3fGtlVyiPE4+wi7QDo0cU/+Gx4mNzvmc6lRjz1c5yKxdYvgwXajSBx2pw
    kTP0iJxI64zv7u3BZEEII6ak9mgUU1CeGZ1KR2Xu80JiWHAYNOiUKCBYHNKDCUYl
    RBErYcAWz2mBpkKyP6hbH16GjXHTTdq5xENmRDHabpHw5o+21LkWBY25EaxjwcZa
    Y3qMIOllTZ2iRrXu7fSP6iDjtFCcE2bFAgMBAAGjZzBlMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUIY7LzqNTzgyTBE5efHb5
    kZ71BUEwHwYDVR0jBBgwFoAUxZA5kifzo4NniQfGKb+4wruTIFowDQYJKoZIhvcN
    AQELBQADggIBAAK207LaqMrnphF6CFQnkMLbskSpDZsKfqqNB52poRvUrNVUOB1w
    3dSEaBUjhFgUU6yzF+xnuH84XVbjD7qlM3YbdiKvJS9jrm71saCKMNc+b9HSeQAU
    DGY7GPb7Y/LG0GKYawYJcPpvRCNnDLsSVn5N4J1foWAWnxuQ6k57ymWwcddibYHD
    OPakOvO4beAnvax3+K5dqF0bh2Np79YolKdIgUVzf4KSBRN4ZE3AOKlBfiKUvWy6
    nRGvu8O/8VaI0vGaOdXvWA5b61H0o5cm50A88tTm2LHxTXynE3AYriHxsWBbRpoM
    oFnmDaQtGY67S6xGfQbwxrwCFd1l7rGsyBQ17cuusOvMNZEEWraLY/738yWKw3qX
    U7KBxdPWPIPd6iDzVjcZrS8AehUEfNQ5yd26gDgW+rZYJoAFYv0vydMEyoI53xXs
    cpY84qV37ZC8wYicugidg9cFtD+1E0nVgOLXPkHnmc7lIDHFiWQKfOieH+KoVCbb
    zdFu3rhW31ygphRmgszkHwApllCTBBMOqMaBpS8eHCnetOITvyB4Kiu1/nKvVxhY
    exit11KQv8F3kTIUQRm0qw00TSBjuQHKoG83yfimlQ8OazciT+aLpVaY8SOrrNnL
    IJ8dHgTpF9WWHxx04DDzqrT7Xq99F9RzDzM7dSizGxIxonoWcBjiF6n5
    -----END CERTIFICATE-----

  token: eyJhbGciOiJBMTI4R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiIxT3Z5ampyc04wZWxjV3l4IiwidGFnIjoiRWpmWWM1TnJhTUw3TGY5cUgwZmtYQSIsInR5cCI6IkpXVCJ9.Dgp9Fztad4RrRT43WJmfnw.KD2DxGyPjDSJE7mQ.jgcnqjVTfjoefcd6t-4WBHuAvpgpVNG3dtgACN4Bm_04GTIS768ihf9Bd6x4wuYOZDA89SffE0MXqs47hMI6QJWzMlkBvkfqeDjuNc6uy4uS1-Kvz9n-seT9IrDbrwSEEsA6U5pO57kGIvYHD3VC3tcAZe4QV5ZYi01PwF3HBFzRE2rq6oL96FmuXcyraNYOEI5vYe9q-6ICp1W8m4bkhf0AwlgZwpDglobi8YEd1RsQZ3Mzw1yuFS-9XbdXmqnKtEV9xZE_TABJ-WmVz6rhs3WSqdxJQwOzJQFuU56w53qiQwtBPoLlkZEWST1lpYtng-73AtY3xXgFr8mFBtQEubxHBXW9dm0PmUiFow8ABeB14iDZRScn121w6j9ar3b9Itdav54mbImY66FBvsIogr8aazrlTrOvqFbqK8EnQTsH8DW4sZGzQoHze-LtEQ-Q8P2vq0gRmOd3CYlYHjsGRsp33mdBOVlFin_NNHa1yOxrDT-H88LkeV5-qaVu5oGpZ3QmDB-VPw7-pKz-SHA41-bTe9-kv9O6GlmDkpS_fOCXuJ3IdcyO528W8Y1h4ElmGfvzOvxRZJrgIreTuE_WZ0ygOEy0vLQwZf1FINfSkHP9EyeBHSelc5PrRYz6jOQFHYnLo3GCrp1qGulm1AOXAdOKCoxOFsc1xXJdtRytfgCwy-9Xg7X2Wq7mys-amEMKJyQ_jTPMGA6Nhg6lMf8he99j9lLZSmhJA2W5a2iwcID143pEq7wil_ZtyOrPAeljufCPhDC5_0FletRJbkmF-ACtCH7ekEQdCAEzR-S7lIHaN2nYw9Ee7kEadn09W5qIzLlao_mtddJB_hEBGCZEhXUgIWU36h3DAZuT7h8tryx7gM_Hf69IRLh0TBhhyBUSt7xN8PP3MHRvLLdXKMo-1CvqNMII-Jwf49XFJiOhNMVN6M_mOB6YOLrTq8TEvlL70Qaw2TwtJX93niP6UYdmDndw1mD8RvtoG-vVzoXMCO9ZG84tE1-PBjqfphr_sw2yNU7mE3wcsA1fgZpBda9oDP8zjR4BZF5R6h0-oWb_m1e-gC6Mm-v_TNmDakHX59xWFHtQx5VrBCwUWFPkhQd4Aw.qmvIAv3dArekmjHxQXKptA
