apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  labels:
    projectcalico.org/tier: default
  name: default.microservice-3
  namespace: dev
spec:
  egress:
  - action: Allow
    destination:
      ports:
      - 80
      selector: role == "database"
    protocol: TCP
    source: {}
  ingress:
  - action: Deny
    destination: {}
    source: {}
  order: 1000
  selector: role == "microservice-3"
  tier: default
  types:
  - Ingress
  - Egress
