apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: peira
spec:
  order: 110

---

apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: peira.peira-control-plane-egress
  namespace: dev
spec:
  egress:
  - action: Allow
    destination: {}
    source: {}
  order: 1000
  selector: app == "peira"
  tier: peira
  types:
  - Egress

---

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: peira.mockservice-egress
spec:
  egress:
  - action: Allow
    destination:
      ports:
      - 6443
      - 443
    protocol: TCP
    source: {}
  - action: Pass
  order: 1000
  selector: peira == "true"
  tier: peira
  types:
  - Ingress
  - Egress

---

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: peira.mockservice-allow-dns
spec:
  egress:
  - action: Allow
    destination:
      selector: k8s-app == "kube-dns"
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      selector: k8s-app == "kube-dns"
    protocol: UDP
    source: {}
  order: 1000
  selector: peira == "true"
  tier: peira
  types:
  - Egress

---

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: peira.mock-allow-proberesult
spec:
  ingress:
  - action: Allow
    destination:
      ports:
      - 9000
    protocol: TCP
    source:
      selector: app == "peira" && component == "operator"
  order: 1000
  selector: peira == "true"
  tier: peira
  types:
  - Ingress

---

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: peira.peira-default-pass
spec:
  egress:
  - action: Pass
    destination: {}
    source: {}
  ingress:
  - action: Pass
    destination: {}
    source: {}
  order: 2000
  selector: peira == "true"
  tier: peira
  types:
  - Ingress
  - Egress

---


kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logserver
  namespace: dev
rules:
- apiGroups:
  - ""
  - "apps"
  - "apiextensions.k8s.io"
  resources:
  - "deployments"
  - "services"
  - "endpoints"
  - "customresourcedefinitions"
  - "events"
  verbs:
  - "*"
- apiGroups: ["peira.tigera.io"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: logserver
  namespace: dev

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logserver
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logserver
subjects:
- kind: ServiceAccount
  name: logserver
  namespace: dev

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: peira-reader
  namespace: dev
rules:
- apiGroups: ["peira.tigera.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: peira-mock
  namespace: dev

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: peira-mock
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: peira-reader
subjects:
- kind: ServiceAccount
  name: peira-mock
  namespace: dev

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: peira-admin
  namespace: dev

---

kind: Service
apiVersion: v1
metadata:
  name: peira-operator
  namespace: dev
spec:
  selector:
    app: peira
    component: operator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: operator

---

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: logserver
  namespace: dev
  labels:
    app: peira
    component: operator
    role: logserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peira
      component: operator
      role: logserver
  template:
    metadata:
      labels:
        app: peira
        component: operator
        role: logserver
    spec:
      imagePullSecrets:
      - name: cnx-pull-secret
      serviceAccount: logserver
      containers:
      - name: operator
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "operator"
        - "--namespace"
        - "dev"
        - "--mockServiceAccount"
        - "peira-mock"
        - "--serviceName"
        - "peira-operator"
        - "--servicePort"
        - "8080"
        - "--pullSecretName"
        - "cnx-pull-secret"
        - "--limitToServiceGraph"
        - "--frequency"
        - "500ms"
        ports:
        - name: operator
          containerPort: 8080
